Service:
  Host: 192.168.1.129
  Port: 8080
  SSL: false
  PrivateKey:
  PublicKey:  
Database:
  Postgre:
    Host: 171.244.49.164
    Port: 5432
    Username: postgres
    Password: xoacdi!@#
    DbName: spin_app
    Schema:
  Redis:
    Host: 103.101.162.65
    Port: 25355 
    Password: Esml429fb
    Database: 9
  Mongo:
    Host: 171.244.49.164
    Port: 2688
    Database: smartid
    Username: admin
    Password: azuasml123456sml
    Auth: admin
Option:
  SmsUrl: 
  SmsApiToken: 
  FireBaseUrl: https://fcm.googleapis.com/fcm/send
  FireBaseToken: key=AAAAtc-5Fto:APA91bFxm1mLGKf9rGaCDu-f6K8cWOqWEO8qR9XYdkwsi4Bng75y9XxeCY6rySPIzpY1EfveXlgWIzTfpnn49TNmjj2pzq7TlcVOuNVB5fu96cDtN59RSXHvEaqIyXHEOfiYHtaSoogm
  EmailSender:
    Server: smtp.gmail.com
    Port: 587
    Email: no-reply@smartlifevn.com
    Password: 1q2w3e4r5t
  ActivateURL: http://localhost:8081/auth/activate
  UpdateContactURL: http://localhost:8081/auth/update-contact
SmsIris:
  Host: https://smsapi2.irismedia.vn/
  SignInRoute: oauth2/token
  SendSmsRoute: api/Sms
  Username: sms_smartlife
  Password: sM@r1L!fe
  Brandname: SMARTLIFE
